'use client'

import { useState } from 'react'
import type { ChapterOutput } from '@/lib/types'
import type { MilestoneDefinition } from '@/lib/milestones'
import type { MilestoneRecord } from '@/lib/types'
import { synthesizeBusinessSummary } from '@/lib/businessSummary'
import { getChaptersForPath } from '@/lib/chapters'

interface ExportTabProps {
  pathId: string
  pathName: string
  completedAt: string
  outputs: ChapterOutput[]
  milestones: MilestoneDefinition[]
  completedMilestones: MilestoneRecord[]
  totalRevenue: number
  totalExpenses: number
}

export default function ExportTab({
  pathId,
  pathName,
  completedAt,
  outputs,
  milestones,
  completedMilestones,
  totalRevenue,
  totalExpenses,
}: ExportTabProps) {
  const [copied, setCopied] = useState(false)
  const summary = synthesizeBusinessSummary(pathId, outputs)
  const chapters = getChaptersForPath(pathId)
  const completedDate = new Date(completedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  const completedKeys = new Set(completedMilestones.map((m) => m.milestone_key))

  function buildPlainText(): string {
    const lines: string[] = []
    lines.push(pathName.toUpperCase())
    lines.push(`Path completed: ${completedDate}`)
    lines.push('')
    lines.push('═'.repeat(50))
    lines.push('')
    lines.push('BUSINESS SUMMARY')
    lines.push('')
    for (const section of summary.sections) {
      lines.push(`  ${section.title}`)
      for (const item of section.items) {
        lines.push(`    ${item.label}: ${item.value}`)
      }
      lines.push('')
    }
    lines.push('═'.repeat(50))
    lines.push('')
    lines.push('CHAPTER DETAILS')
    lines.push('')
    for (const chapter of chapters) {
      const output = outputs.find((o) => o.chapter_id === chapter.id)
      lines.push(`  Chapter ${chapter.sequence}: ${chapter.title}`)
      if (output?.outputs) {
        for (const field of chapter.requiredOutputs) {
          const value = output.outputs[field.fieldName]
          if (value) lines.push(`    ${field.label}: ${value}`)
        }
      }
      lines.push('')
    }
    lines.push('═'.repeat(50))
    lines.push('')
    lines.push('MILESTONES')
    lines.push('')
    for (const m of milestones) {
      const done = completedKeys.has(m.key)
      lines.push(`  ${done ? '[x]' : '[ ]'} ${m.title}`)
    }
    lines.push('')
    if (totalRevenue > 0 || totalExpenses > 0) {
      lines.push('═'.repeat(50))
      lines.push('')
      lines.push('FINANCIAL SUMMARY')
      lines.push(`  Total Revenue:  $${totalRevenue.toFixed(2)}`)
      lines.push(`  Total Expenses: $${totalExpenses.toFixed(2)}`)
      lines.push(`  Net Profit:     $${(totalRevenue - totalExpenses).toFixed(2)}`)
      lines.push('')
    }
    lines.push('═'.repeat(50))
    lines.push('Generated by Startpath')
    return lines.join('\n')
  }

  function handleCopy() {
    navigator.clipboard.writeText(buildPlainText())
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  function handlePrint() {
    window.print()
  }

  return (
    <div>
      <div className="flex gap-4 mb-8">
        <button onClick={handlePrint} className="btn btn-primary btn-shine">
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          Download as PDF
        </button>
        <button onClick={handleCopy} className="btn btn-secondary">
          {copied ? (
            <>
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" style={{ color: 'var(--color-success)' }}>
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
              Copied!
            </>
          ) : (
            <>
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
              </svg>
              Copy as text
            </>
          )}
        </button>
      </div>

      <div id="export-content" className="space-y-6">
        <div
          className="card p-8 glow-border-always print:bg-white print:border-black"
          style={{ background: 'linear-gradient(135deg, var(--color-surface-1) 0%, var(--color-surface-2) 100%)' }}
        >
          <h2 className="text-3xl font-bold mb-2 print:text-black" style={{ color: 'var(--color-text-primary)', letterSpacing: '-0.02em' }}>
            {pathName}
          </h2>
          <p style={{ color: 'var(--color-text-tertiary)' }} className="print:text-gray-600">
            Path completed {completedDate}
          </p>
        </div>

        <div className="card p-8 print:bg-white print:border-black">
          <h3 className="stat-label mb-6">Business Summary</h3>
          <div className="space-y-6">
            {summary.sections.map((section) => (
              <div key={section.title}>
                <h4 className="font-medium mb-3 print:text-black" style={{ color: 'var(--color-text-primary)' }}>{section.title}</h4>
                <div className="space-y-2">
                  {section.items.map((item) => (
                    <div key={item.label}>
                      <span className="text-sm" style={{ color: 'var(--color-text-muted)' }}>{item.label}: </span>
                      <span className="text-sm print:text-black" style={{ color: 'var(--color-text-secondary)' }}>{item.value}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="card p-8 print:bg-white print:border-black">
          <h3 className="stat-label mb-6">Chapter Details</h3>
          <div className="space-y-6">
            {chapters.map((chapter) => {
              const output = outputs.find((o) => o.chapter_id === chapter.id)
              return (
                <div key={chapter.id} className="pb-6 last:pb-0 print:border-gray-300" style={{ borderBottom: '1px solid var(--color-border-subtle)' }}>
                  <h4 className="font-medium mb-3 print:text-black" style={{ color: 'var(--color-text-primary)' }}>
                    Chapter {chapter.sequence}: {chapter.title}
                  </h4>
                  {output?.outputs && (
                    <div className="space-y-2">
                      {chapter.requiredOutputs.map((field) => {
                        const value = output.outputs[field.fieldName]
                        if (!value) return null
                        return (
                          <div key={field.fieldName}>
                            <span className="text-sm" style={{ color: 'var(--color-text-muted)' }}>{field.label}: </span>
                            <span className="text-sm print:text-black" style={{ color: 'var(--color-text-secondary)' }}>{value}</span>
                          </div>
                        )
                      })}
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        </div>

        <div className="card p-8 print:bg-white print:border-black">
          <h3 className="stat-label mb-6">Milestones</h3>
          <div className="space-y-3">
            {milestones.map((m) => {
              const done = completedKeys.has(m.key)
              return (
                <div key={m.key} className="flex items-center gap-3">
                  {done ? (
                    <svg className="w-5 h-5 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" style={{ color: 'var(--color-success)' }}>
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                  ) : (
                    <svg className="w-5 h-5 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" style={{ color: 'var(--color-text-muted)' }}>
                      <circle cx="12" cy="12" r="9" strokeWidth={2} />
                    </svg>
                  )}
                  <span className="text-sm print:text-black" style={{ color: done ? 'var(--color-text-primary)' : 'var(--color-text-muted)' }}>{m.title}</span>
                </div>
              )
            })}
          </div>
        </div>

        {(totalRevenue > 0 || totalExpenses > 0) && (
          <div className="card p-8 print:bg-white print:border-black">
            <h3 className="stat-label mb-6">Financial Summary</h3>
            <div className="grid grid-cols-3 gap-4">
              <div className="stat-card">
                <p className="stat-label">Total Revenue</p>
                <p className="stat-value text-2xl print:text-black" style={{ color: 'var(--color-success)' }}>${totalRevenue.toFixed(2)}</p>
              </div>
              <div className="stat-card">
                <p className="stat-label">Total Expenses</p>
                <p className="stat-value text-2xl print:text-black" style={{ color: 'var(--color-danger)' }}>${totalExpenses.toFixed(2)}</p>
              </div>
              <div className="stat-card">
                <p className="stat-label">Net Profit</p>
                <p className="stat-value text-2xl print:text-black" style={{ color: totalRevenue - totalExpenses >= 0 ? 'var(--color-text-primary)' : 'var(--color-danger)' }}>
                  ${(totalRevenue - totalExpenses).toFixed(2)}
                </p>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
